title: Lab 8
remote_theme: just-the-docs/just-the-docs

nav_external_links:
  - title: 1. Installing Softwares or Import softwares
    url: lab8%20batch_data_pipeline.html#1-installing-softwares-or-import-softwares
  - title: 1.0 Import Amazon Machine Images (AMIs) into your EC2 instance
    url: lab8%20batch_data_pipeline.html#10-import-amazon-machine-images-amis-into-your-ec2-instance
  - title: 2. Scenario Carpark system (daily reporting)
    url: lab8%20batch_data_pipeline.html#2-scenario-carpark-system-daily-reporting
  - title: 2.1 import libraries
    url: lab8%20batch_data_pipeline.html#21-import-libraries
  - title: 2.2 Prepare data
    url: lab8%20batch_data_pipeline.html#22-prepare-data
  - title: 2.3 Insert, Select, Delete data in postgresql
    url: lab8%20batch_data_pipeline.html#23-insert-select-delete-data-in-postgresql
  - title: 2.4 Generate car entry and exit every 5 minutes
    url: lab8%20batch_data_pipeline.html#24-generate-car-entry-and-exit-every-5-minutes
  - title: Conclusion
    url: lab8%20batch_data_pipeline.html#conclusion
  - title: Submissions next Wed 9pm (8 Oct 2025)
    url: lab8%20batch_data_pipeline.html#submissions-next-wed-9pm-15-oct-2025

just_the_docs:
  custom_css:
    - assets/css/style.scss
    - assets/js/fix-links.js

