title: Lab 8
remote_theme: just-the-docs/just-the-docs

nav_external_links:
  - title: 1. Installing Softwares or Import softwares
    url: lab7%20manual_data_pipeline.html#1-scenario
  - title: 2. Prepare Python Environment
    url: lab7%20manual_data_pipeline.html#2-prepare-python-environment
  - title: 3. Generate data
    url: lab7%20manual_data_pipeline.html#3-generate-data
  - title: 4. Python Visualisation
    url: lab7%20manual_data_pipeline.html#4-python-visualisation
  - title: 5. Microsoft Excel (Pivot Tables)
    url: lab7%20manual_data_pipeline.html#5-microsoft-excel-pivot-tables
  - title: 6. Microsoft Power BI
    url: lab7%20manual_data_pipeline.html#6-microsoft-power-bi
  - title: Conclusion
    url: lab7%20manual_data_pipeline.html#conclusion
  - title: Submissions next Wed 9pm (8 Oct 2025)
    url: lab7%20manual_data_pipeline.html#submissions-next-wed-9pm-8-oct-2025

just_the_docs:
  custom_css:
    - assets/css/style.scss
    - assets/js/fix-links.js

